/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ProjectRouteImport } from './routes/_project'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as ShellSettingsRouteImport } from './routes/_shell/settings'
import { Route as ShellProjectsRouteImport } from './routes/_shell/projects'
import { Route as ShellDatabasesRouteImport } from './routes/_shell/databases'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/_project/$projectId/index'
import { Route as ProjectProjectIdSettingsRouteImport } from './routes/_project/$projectId/settings'
import { Route as ProjectProjectIdDeploymentsRouteImport } from './routes/_project/$projectId/deployments'
import { Route as ProjectProjectIdServicesServiceIdRouteImport } from './routes/_project/$projectId/services/$serviceId'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/_project',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)
const ShellProjectsRoute = ShellProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDatabasesRoute = ShellDatabasesRouteImport.update({
  id: '/databases',
  path: '/databases',
  getParentRoute: () => ShellRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectProjectIdSettingsRoute =
  ProjectProjectIdSettingsRouteImport.update({
    id: '/$projectId/settings',
    path: '/$projectId/settings',
    getParentRoute: () => ProjectRoute,
  } as any)
const ProjectProjectIdDeploymentsRoute =
  ProjectProjectIdDeploymentsRouteImport.update({
    id: '/$projectId/deployments',
    path: '/$projectId/deployments',
    getParentRoute: () => ProjectRoute,
  } as any)
const ProjectProjectIdServicesServiceIdRoute =
  ProjectProjectIdServicesServiceIdRouteImport.update({
    id: '/$projectId/services/$serviceId',
    path: '/$projectId/services/$serviceId',
    getParentRoute: () => ProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof ShellIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/databases': typeof ShellDatabasesRoute
  '/projects': typeof ShellProjectsRoute
  '/settings': typeof ShellSettingsRoute
  '/$projectId/deployments': typeof ProjectProjectIdDeploymentsRoute
  '/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/$projectId/': typeof ProjectProjectIdIndexRoute
  '/$projectId/services/$serviceId': typeof ProjectProjectIdServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof ShellIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/databases': typeof ShellDatabasesRoute
  '/projects': typeof ShellProjectsRoute
  '/settings': typeof ShellSettingsRoute
  '/$projectId/deployments': typeof ProjectProjectIdDeploymentsRoute
  '/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/$projectId': typeof ProjectProjectIdIndexRoute
  '/$projectId/services/$serviceId': typeof ProjectProjectIdServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_project': typeof ProjectRouteWithChildren
  '/_shell': typeof ShellRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_shell/databases': typeof ShellDatabasesRoute
  '/_shell/projects': typeof ShellProjectsRoute
  '/_shell/settings': typeof ShellSettingsRoute
  '/_shell/': typeof ShellIndexRoute
  '/_project/$projectId/deployments': typeof ProjectProjectIdDeploymentsRoute
  '/_project/$projectId/settings': typeof ProjectProjectIdSettingsRoute
  '/_project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/_project/$projectId/services/$serviceId': typeof ProjectProjectIdServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/databases'
    | '/projects'
    | '/settings'
    | '/$projectId/deployments'
    | '/$projectId/settings'
    | '/$projectId/'
    | '/$projectId/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/databases'
    | '/projects'
    | '/settings'
    | '/$projectId/deployments'
    | '/$projectId/settings'
    | '/$projectId'
    | '/$projectId/services/$serviceId'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_project'
    | '/_shell'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_shell/databases'
    | '/_shell/projects'
    | '/_shell/settings'
    | '/_shell/'
    | '/_project/$projectId/deployments'
    | '/_project/$projectId/settings'
    | '/_project/$projectId/'
    | '/_project/$projectId/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProjectRoute: typeof ProjectRouteWithChildren
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_project': {
      id: '/_project'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/projects': {
      id: '/_shell/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ShellProjectsRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/databases': {
      id: '/_shell/databases'
      path: '/databases'
      fullPath: '/databases'
      preLoaderRoute: typeof ShellDatabasesRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_project/$projectId/': {
      id: '/_project/$projectId/'
      path: '/$projectId'
      fullPath: '/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/_project/$projectId/settings': {
      id: '/_project/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/$projectId/settings'
      preLoaderRoute: typeof ProjectProjectIdSettingsRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/_project/$projectId/deployments': {
      id: '/_project/$projectId/deployments'
      path: '/$projectId/deployments'
      fullPath: '/$projectId/deployments'
      preLoaderRoute: typeof ProjectProjectIdDeploymentsRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/_project/$projectId/services/$serviceId': {
      id: '/_project/$projectId/services/$serviceId'
      path: '/$projectId/services/$serviceId'
      fullPath: '/$projectId/services/$serviceId'
      preLoaderRoute: typeof ProjectProjectIdServicesServiceIdRouteImport
      parentRoute: typeof ProjectRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProjectRouteChildren {
  ProjectProjectIdDeploymentsRoute: typeof ProjectProjectIdDeploymentsRoute
  ProjectProjectIdSettingsRoute: typeof ProjectProjectIdSettingsRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdServicesServiceIdRoute: typeof ProjectProjectIdServicesServiceIdRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectProjectIdDeploymentsRoute: ProjectProjectIdDeploymentsRoute,
  ProjectProjectIdSettingsRoute: ProjectProjectIdSettingsRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdServicesServiceIdRoute:
    ProjectProjectIdServicesServiceIdRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

interface ShellRouteChildren {
  ShellDatabasesRoute: typeof ShellDatabasesRoute
  ShellProjectsRoute: typeof ShellProjectsRoute
  ShellSettingsRoute: typeof ShellSettingsRoute
  ShellIndexRoute: typeof ShellIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDatabasesRoute: ShellDatabasesRoute,
  ShellProjectsRoute: ShellProjectsRoute,
  ShellSettingsRoute: ShellSettingsRoute,
  ShellIndexRoute: ShellIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  ProjectRoute: ProjectRouteWithChildren,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
