/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as SplatRouteImport } from './routes/$'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardUsersRouteImport } from './routes/_dashboard.users'
import { Route as DashboardTemplatesRouteImport } from './routes/_dashboard.templates'
import { Route as DashboardStorageRouteImport } from './routes/_dashboard.storage'
import { Route as DashboardSourcesRouteImport } from './routes/_dashboard.sources'
import { Route as DashboardSettingsRouteImport } from './routes/_dashboard.settings'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardJobsRouteImport } from './routes/_dashboard.jobs'
import { Route as DashboardDomainsRouteImport } from './routes/_dashboard.domains'
import { Route as DashboardDeploymentsRouteImport } from './routes/_dashboard.deployments'
import { Route as DashboardAuditLogsRouteImport } from './routes/_dashboard.audit-logs'
import { Route as DashboardAiRouteImport } from './routes/_dashboard.ai'
import { Route as AuthSignupRouteImport } from './routes/_auth.signup'
import { Route as AuthSigninRouteImport } from './routes/_auth.signin'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth.reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth.forgot-password'
import { Route as DashboardSettingsIndexRouteImport } from './routes/_dashboard.settings/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard.profile/index'
import { Route as DashboardSettingsUpdatesRouteImport } from './routes/_dashboard.settings/updates'
import { Route as DashboardSettingsOauthRouteImport } from './routes/_dashboard.settings/oauth'
import { Route as DashboardSettingsNotificationsRouteImport } from './routes/_dashboard.settings/notifications'
import { Route as DashboardSettingsMigrationRouteImport } from './routes/_dashboard.settings/migration'
import { Route as DashboardSettingsMaintenanceRouteImport } from './routes/_dashboard.settings/maintenance'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/_dashboard.settings/general'
import { Route as DashboardSettingsDnsRouteImport } from './routes/_dashboard.settings/dns'
import { Route as DashboardSettingsBackupsRouteImport } from './routes/_dashboard.settings/backups'
import { Route as DashboardSettingsApiRouteImport } from './routes/_dashboard.settings/api'
import { Route as DashboardServicesServiceIdIndexRouteImport } from './routes/_dashboard.services/$serviceId.index'
import { Route as DashboardProjectsProjectIdIndexRouteImport } from './routes/_dashboard.projects/$projectId.index'
import { Route as DashboardServicesServiceIdVariablesRouteImport } from './routes/_dashboard.services/$serviceId.variables'
import { Route as DashboardServicesServiceIdTerminalRouteImport } from './routes/_dashboard.services/$serviceId.terminal'
import { Route as DashboardServicesServiceIdServerlessRouteImport } from './routes/_dashboard.services/$serviceId.serverless'
import { Route as DashboardServicesServiceIdDomainsRouteImport } from './routes/_dashboard.services/$serviceId.domains'
import { Route as DashboardServicesServiceIdDeploymentsRouteImport } from './routes/_dashboard.services/$serviceId.deployments'
import { Route as DashboardServicesServiceIdBuildRouteImport } from './routes/_dashboard.services/$serviceId.build'
import { Route as DashboardProjectsProjectIdSettingsRouteImport } from './routes/_dashboard.projects/$projectId.settings'
import { Route as DashboardProjectsProjectIdJobsRouteImport } from './routes/_dashboard.projects/$projectId.jobs'
import { Route as DashboardProjectsProjectIdComposeRouteImport } from './routes/_dashboard.projects/$projectId.compose'
import { Route as DashboardProjectsProjectIdCanvasRouteImport } from './routes/_dashboard.projects/$projectId.canvas'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardUsersRoute = DashboardUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStorageRoute = DashboardStorageRouteImport.update({
  id: '/storage',
  path: '/storage',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSourcesRoute = DashboardSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardJobsRoute = DashboardJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDomainsRoute = DashboardDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDeploymentsRoute = DashboardDeploymentsRouteImport.update({
  id: '/deployments',
  path: '/deployments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditLogsRoute = DashboardAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsUpdatesRoute =
  DashboardSettingsUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsOauthRoute = DashboardSettingsOauthRouteImport.update({
  id: '/oauth',
  path: '/oauth',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsNotificationsRoute =
  DashboardSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsMigrationRoute =
  DashboardSettingsMigrationRouteImport.update({
    id: '/migration',
    path: '/migration',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsMaintenanceRoute =
  DashboardSettingsMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsDnsRoute = DashboardSettingsDnsRouteImport.update({
  id: '/dns',
  path: '/dns',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsBackupsRoute =
  DashboardSettingsBackupsRouteImport.update({
    id: '/backups',
    path: '/backups',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsApiRoute = DashboardSettingsApiRouteImport.update({
  id: '/api',
  path: '/api',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardServicesServiceIdIndexRoute =
  DashboardServicesServiceIdIndexRouteImport.update({
    id: '/services/$serviceId/',
    path: '/services/$serviceId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdIndexRoute =
  DashboardProjectsProjectIdIndexRouteImport.update({
    id: '/$projectId/',
    path: '/$projectId/',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardServicesServiceIdVariablesRoute =
  DashboardServicesServiceIdVariablesRouteImport.update({
    id: '/services/$serviceId/variables',
    path: '/services/$serviceId/variables',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdTerminalRoute =
  DashboardServicesServiceIdTerminalRouteImport.update({
    id: '/services/$serviceId/terminal',
    path: '/services/$serviceId/terminal',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdServerlessRoute =
  DashboardServicesServiceIdServerlessRouteImport.update({
    id: '/services/$serviceId/serverless',
    path: '/services/$serviceId/serverless',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdDomainsRoute =
  DashboardServicesServiceIdDomainsRouteImport.update({
    id: '/services/$serviceId/domains',
    path: '/services/$serviceId/domains',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdDeploymentsRoute =
  DashboardServicesServiceIdDeploymentsRouteImport.update({
    id: '/services/$serviceId/deployments',
    path: '/services/$serviceId/deployments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardServicesServiceIdBuildRoute =
  DashboardServicesServiceIdBuildRouteImport.update({
    id: '/services/$serviceId/build',
    path: '/services/$serviceId/build',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProjectsProjectIdSettingsRoute =
  DashboardProjectsProjectIdSettingsRouteImport.update({
    id: '/$projectId/settings',
    path: '/$projectId/settings',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdJobsRoute =
  DashboardProjectsProjectIdJobsRouteImport.update({
    id: '/$projectId/jobs',
    path: '/$projectId/jobs',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdComposeRoute =
  DashboardProjectsProjectIdComposeRouteImport.update({
    id: '/$projectId/compose',
    path: '/$projectId/compose',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsProjectIdCanvasRoute =
  DashboardProjectsProjectIdCanvasRouteImport.update({
    id: '/$projectId/canvas',
    path: '/$projectId/canvas',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/ai': typeof DashboardAiRoute
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/domains': typeof DashboardDomainsRoute
  '/jobs': typeof DashboardJobsRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/settings': typeof DashboardSettingsRouteWithChildren
  '/sources': typeof DashboardSourcesRoute
  '/storage': typeof DashboardStorageRoute
  '/templates': typeof DashboardTemplatesRoute
  '/users': typeof DashboardUsersRoute
  '/settings/api': typeof DashboardSettingsApiRoute
  '/settings/backups': typeof DashboardSettingsBackupsRoute
  '/settings/dns': typeof DashboardSettingsDnsRoute
  '/settings/general': typeof DashboardSettingsGeneralRoute
  '/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/settings/migration': typeof DashboardSettingsMigrationRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/oauth': typeof DashboardSettingsOauthRoute
  '/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/profile/': typeof DashboardProfileIndexRoute
  '/settings/': typeof DashboardSettingsIndexRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/$': typeof SplatRoute
  '/': typeof DashboardIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signin': typeof AuthSigninRoute
  '/signup': typeof AuthSignupRoute
  '/ai': typeof DashboardAiRoute
  '/audit-logs': typeof DashboardAuditLogsRoute
  '/deployments': typeof DashboardDeploymentsRoute
  '/domains': typeof DashboardDomainsRoute
  '/jobs': typeof DashboardJobsRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/sources': typeof DashboardSourcesRoute
  '/storage': typeof DashboardStorageRoute
  '/templates': typeof DashboardTemplatesRoute
  '/users': typeof DashboardUsersRoute
  '/settings/api': typeof DashboardSettingsApiRoute
  '/settings/backups': typeof DashboardSettingsBackupsRoute
  '/settings/dns': typeof DashboardSettingsDnsRoute
  '/settings/general': typeof DashboardSettingsGeneralRoute
  '/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/settings/migration': typeof DashboardSettingsMigrationRoute
  '/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/settings/oauth': typeof DashboardSettingsOauthRoute
  '/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/settings': typeof DashboardSettingsIndexRoute
  '/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/projects/$projectId': typeof DashboardProjectsProjectIdIndexRoute
  '/services/$serviceId': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$': typeof SplatRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signin': typeof AuthSigninRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_dashboard/ai': typeof DashboardAiRoute
  '/_dashboard/audit-logs': typeof DashboardAuditLogsRoute
  '/_dashboard/deployments': typeof DashboardDeploymentsRoute
  '/_dashboard/domains': typeof DashboardDomainsRoute
  '/_dashboard/jobs': typeof DashboardJobsRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/_dashboard/sources': typeof DashboardSourcesRoute
  '/_dashboard/storage': typeof DashboardStorageRoute
  '/_dashboard/templates': typeof DashboardTemplatesRoute
  '/_dashboard/users': typeof DashboardUsersRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/settings/api': typeof DashboardSettingsApiRoute
  '/_dashboard/settings/backups': typeof DashboardSettingsBackupsRoute
  '/_dashboard/settings/dns': typeof DashboardSettingsDnsRoute
  '/_dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/_dashboard/settings/maintenance': typeof DashboardSettingsMaintenanceRoute
  '/_dashboard/settings/migration': typeof DashboardSettingsMigrationRoute
  '/_dashboard/settings/notifications': typeof DashboardSettingsNotificationsRoute
  '/_dashboard/settings/oauth': typeof DashboardSettingsOauthRoute
  '/_dashboard/settings/updates': typeof DashboardSettingsUpdatesRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/settings/': typeof DashboardSettingsIndexRoute
  '/_dashboard/projects/$projectId/canvas': typeof DashboardProjectsProjectIdCanvasRoute
  '/_dashboard/projects/$projectId/compose': typeof DashboardProjectsProjectIdComposeRoute
  '/_dashboard/projects/$projectId/jobs': typeof DashboardProjectsProjectIdJobsRoute
  '/_dashboard/projects/$projectId/settings': typeof DashboardProjectsProjectIdSettingsRoute
  '/_dashboard/services/$serviceId/build': typeof DashboardServicesServiceIdBuildRoute
  '/_dashboard/services/$serviceId/deployments': typeof DashboardServicesServiceIdDeploymentsRoute
  '/_dashboard/services/$serviceId/domains': typeof DashboardServicesServiceIdDomainsRoute
  '/_dashboard/services/$serviceId/serverless': typeof DashboardServicesServiceIdServerlessRoute
  '/_dashboard/services/$serviceId/terminal': typeof DashboardServicesServiceIdTerminalRoute
  '/_dashboard/services/$serviceId/variables': typeof DashboardServicesServiceIdVariablesRoute
  '/_dashboard/projects/$projectId/': typeof DashboardProjectsProjectIdIndexRoute
  '/_dashboard/services/$serviceId/': typeof DashboardServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$'
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/ai'
    | '/audit-logs'
    | '/deployments'
    | '/domains'
    | '/jobs'
    | '/projects'
    | '/settings'
    | '/sources'
    | '/storage'
    | '/templates'
    | '/users'
    | '/settings/api'
    | '/settings/backups'
    | '/settings/dns'
    | '/settings/general'
    | '/settings/maintenance'
    | '/settings/migration'
    | '/settings/notifications'
    | '/settings/oauth'
    | '/settings/updates'
    | '/profile/'
    | '/settings/'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/jobs'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/projects/$projectId/'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$'
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/reset-password'
    | '/signin'
    | '/signup'
    | '/ai'
    | '/audit-logs'
    | '/deployments'
    | '/domains'
    | '/jobs'
    | '/projects'
    | '/sources'
    | '/storage'
    | '/templates'
    | '/users'
    | '/settings/api'
    | '/settings/backups'
    | '/settings/dns'
    | '/settings/general'
    | '/settings/maintenance'
    | '/settings/migration'
    | '/settings/notifications'
    | '/settings/oauth'
    | '/settings/updates'
    | '/profile'
    | '/settings'
    | '/projects/$projectId/canvas'
    | '/projects/$projectId/compose'
    | '/projects/$projectId/jobs'
    | '/projects/$projectId/settings'
    | '/services/$serviceId/build'
    | '/services/$serviceId/deployments'
    | '/services/$serviceId/domains'
    | '/services/$serviceId/serverless'
    | '/services/$serviceId/terminal'
    | '/services/$serviceId/variables'
    | '/projects/$projectId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/$'
    | '/_auth'
    | '/_dashboard'
    | '/onboarding'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/signin'
    | '/_auth/signup'
    | '/_dashboard/ai'
    | '/_dashboard/audit-logs'
    | '/_dashboard/deployments'
    | '/_dashboard/domains'
    | '/_dashboard/jobs'
    | '/_dashboard/projects'
    | '/_dashboard/settings'
    | '/_dashboard/sources'
    | '/_dashboard/storage'
    | '/_dashboard/templates'
    | '/_dashboard/users'
    | '/_dashboard/'
    | '/_dashboard/settings/api'
    | '/_dashboard/settings/backups'
    | '/_dashboard/settings/dns'
    | '/_dashboard/settings/general'
    | '/_dashboard/settings/maintenance'
    | '/_dashboard/settings/migration'
    | '/_dashboard/settings/notifications'
    | '/_dashboard/settings/oauth'
    | '/_dashboard/settings/updates'
    | '/_dashboard/profile/'
    | '/_dashboard/settings/'
    | '/_dashboard/projects/$projectId/canvas'
    | '/_dashboard/projects/$projectId/compose'
    | '/_dashboard/projects/$projectId/jobs'
    | '/_dashboard/projects/$projectId/settings'
    | '/_dashboard/services/$serviceId/build'
    | '/_dashboard/services/$serviceId/deployments'
    | '/_dashboard/services/$serviceId/domains'
    | '/_dashboard/services/$serviceId/serverless'
    | '/_dashboard/services/$serviceId/terminal'
    | '/_dashboard/services/$serviceId/variables'
    | '/_dashboard/projects/$projectId/'
    | '/_dashboard/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/users': {
      id: '/_dashboard/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof DashboardUsersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/templates': {
      id: '/_dashboard/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/storage': {
      id: '/_dashboard/storage'
      path: '/storage'
      fullPath: '/storage'
      preLoaderRoute: typeof DashboardStorageRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/sources': {
      id: '/_dashboard/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof DashboardSourcesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings': {
      id: '/_dashboard/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/jobs': {
      id: '/_dashboard/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof DashboardJobsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/domains': {
      id: '/_dashboard/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DashboardDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/deployments': {
      id: '/_dashboard/deployments'
      path: '/deployments'
      fullPath: '/deployments'
      preLoaderRoute: typeof DashboardDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/audit-logs': {
      id: '/_dashboard/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof DashboardAuditLogsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/ai': {
      id: '/_dashboard/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signin': {
      id: '/_auth/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/settings/updates': {
      id: '/_dashboard/settings/updates'
      path: '/updates'
      fullPath: '/settings/updates'
      preLoaderRoute: typeof DashboardSettingsUpdatesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/oauth': {
      id: '/_dashboard/settings/oauth'
      path: '/oauth'
      fullPath: '/settings/oauth'
      preLoaderRoute: typeof DashboardSettingsOauthRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/notifications': {
      id: '/_dashboard/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof DashboardSettingsNotificationsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/migration': {
      id: '/_dashboard/settings/migration'
      path: '/migration'
      fullPath: '/settings/migration'
      preLoaderRoute: typeof DashboardSettingsMigrationRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/maintenance': {
      id: '/_dashboard/settings/maintenance'
      path: '/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof DashboardSettingsMaintenanceRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/general': {
      id: '/_dashboard/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/dns': {
      id: '/_dashboard/settings/dns'
      path: '/dns'
      fullPath: '/settings/dns'
      preLoaderRoute: typeof DashboardSettingsDnsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/backups': {
      id: '/_dashboard/settings/backups'
      path: '/backups'
      fullPath: '/settings/backups'
      preLoaderRoute: typeof DashboardSettingsBackupsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/settings/api': {
      id: '/_dashboard/settings/api'
      path: '/api'
      fullPath: '/settings/api'
      preLoaderRoute: typeof DashboardSettingsApiRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/_dashboard/services/$serviceId/': {
      id: '/_dashboard/services/$serviceId/'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof DashboardServicesServiceIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId/': {
      id: '/_dashboard/projects/$projectId/'
      path: '/$projectId'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/services/$serviceId/variables': {
      id: '/_dashboard/services/$serviceId/variables'
      path: '/services/$serviceId/variables'
      fullPath: '/services/$serviceId/variables'
      preLoaderRoute: typeof DashboardServicesServiceIdVariablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/terminal': {
      id: '/_dashboard/services/$serviceId/terminal'
      path: '/services/$serviceId/terminal'
      fullPath: '/services/$serviceId/terminal'
      preLoaderRoute: typeof DashboardServicesServiceIdTerminalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/serverless': {
      id: '/_dashboard/services/$serviceId/serverless'
      path: '/services/$serviceId/serverless'
      fullPath: '/services/$serviceId/serverless'
      preLoaderRoute: typeof DashboardServicesServiceIdServerlessRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/domains': {
      id: '/_dashboard/services/$serviceId/domains'
      path: '/services/$serviceId/domains'
      fullPath: '/services/$serviceId/domains'
      preLoaderRoute: typeof DashboardServicesServiceIdDomainsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/deployments': {
      id: '/_dashboard/services/$serviceId/deployments'
      path: '/services/$serviceId/deployments'
      fullPath: '/services/$serviceId/deployments'
      preLoaderRoute: typeof DashboardServicesServiceIdDeploymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/services/$serviceId/build': {
      id: '/_dashboard/services/$serviceId/build'
      path: '/services/$serviceId/build'
      fullPath: '/services/$serviceId/build'
      preLoaderRoute: typeof DashboardServicesServiceIdBuildRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects/$projectId/settings': {
      id: '/_dashboard/projects/$projectId/settings'
      path: '/$projectId/settings'
      fullPath: '/projects/$projectId/settings'
      preLoaderRoute: typeof DashboardProjectsProjectIdSettingsRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/jobs': {
      id: '/_dashboard/projects/$projectId/jobs'
      path: '/$projectId/jobs'
      fullPath: '/projects/$projectId/jobs'
      preLoaderRoute: typeof DashboardProjectsProjectIdJobsRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/compose': {
      id: '/_dashboard/projects/$projectId/compose'
      path: '/$projectId/compose'
      fullPath: '/projects/$projectId/compose'
      preLoaderRoute: typeof DashboardProjectsProjectIdComposeRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/canvas': {
      id: '/_dashboard/projects/$projectId/canvas'
      path: '/$projectId/canvas'
      fullPath: '/projects/$projectId/canvas'
      preLoaderRoute: typeof DashboardProjectsProjectIdCanvasRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSigninRoute: AuthSigninRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdCanvasRoute: typeof DashboardProjectsProjectIdCanvasRoute
  DashboardProjectsProjectIdComposeRoute: typeof DashboardProjectsProjectIdComposeRoute
  DashboardProjectsProjectIdJobsRoute: typeof DashboardProjectsProjectIdJobsRoute
  DashboardProjectsProjectIdSettingsRoute: typeof DashboardProjectsProjectIdSettingsRoute
  DashboardProjectsProjectIdIndexRoute: typeof DashboardProjectsProjectIdIndexRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdCanvasRoute: DashboardProjectsProjectIdCanvasRoute,
  DashboardProjectsProjectIdComposeRoute:
    DashboardProjectsProjectIdComposeRoute,
  DashboardProjectsProjectIdJobsRoute: DashboardProjectsProjectIdJobsRoute,
  DashboardProjectsProjectIdSettingsRoute:
    DashboardProjectsProjectIdSettingsRoute,
  DashboardProjectsProjectIdIndexRoute: DashboardProjectsProjectIdIndexRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardSettingsRouteChildren {
  DashboardSettingsApiRoute: typeof DashboardSettingsApiRoute
  DashboardSettingsBackupsRoute: typeof DashboardSettingsBackupsRoute
  DashboardSettingsDnsRoute: typeof DashboardSettingsDnsRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsMaintenanceRoute: typeof DashboardSettingsMaintenanceRoute
  DashboardSettingsMigrationRoute: typeof DashboardSettingsMigrationRoute
  DashboardSettingsNotificationsRoute: typeof DashboardSettingsNotificationsRoute
  DashboardSettingsOauthRoute: typeof DashboardSettingsOauthRoute
  DashboardSettingsUpdatesRoute: typeof DashboardSettingsUpdatesRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsApiRoute: DashboardSettingsApiRoute,
  DashboardSettingsBackupsRoute: DashboardSettingsBackupsRoute,
  DashboardSettingsDnsRoute: DashboardSettingsDnsRoute,
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
  DashboardSettingsMaintenanceRoute: DashboardSettingsMaintenanceRoute,
  DashboardSettingsMigrationRoute: DashboardSettingsMigrationRoute,
  DashboardSettingsNotificationsRoute: DashboardSettingsNotificationsRoute,
  DashboardSettingsOauthRoute: DashboardSettingsOauthRoute,
  DashboardSettingsUpdatesRoute: DashboardSettingsUpdatesRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAuditLogsRoute: typeof DashboardAuditLogsRoute
  DashboardDeploymentsRoute: typeof DashboardDeploymentsRoute
  DashboardDomainsRoute: typeof DashboardDomainsRoute
  DashboardJobsRoute: typeof DashboardJobsRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardSourcesRoute: typeof DashboardSourcesRoute
  DashboardStorageRoute: typeof DashboardStorageRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardUsersRoute: typeof DashboardUsersRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardServicesServiceIdBuildRoute: typeof DashboardServicesServiceIdBuildRoute
  DashboardServicesServiceIdDeploymentsRoute: typeof DashboardServicesServiceIdDeploymentsRoute
  DashboardServicesServiceIdDomainsRoute: typeof DashboardServicesServiceIdDomainsRoute
  DashboardServicesServiceIdServerlessRoute: typeof DashboardServicesServiceIdServerlessRoute
  DashboardServicesServiceIdTerminalRoute: typeof DashboardServicesServiceIdTerminalRoute
  DashboardServicesServiceIdVariablesRoute: typeof DashboardServicesServiceIdVariablesRoute
  DashboardServicesServiceIdIndexRoute: typeof DashboardServicesServiceIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardAuditLogsRoute: DashboardAuditLogsRoute,
  DashboardDeploymentsRoute: DashboardDeploymentsRoute,
  DashboardDomainsRoute: DashboardDomainsRoute,
  DashboardJobsRoute: DashboardJobsRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardSourcesRoute: DashboardSourcesRoute,
  DashboardStorageRoute: DashboardStorageRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardUsersRoute: DashboardUsersRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardServicesServiceIdBuildRoute: DashboardServicesServiceIdBuildRoute,
  DashboardServicesServiceIdDeploymentsRoute:
    DashboardServicesServiceIdDeploymentsRoute,
  DashboardServicesServiceIdDomainsRoute:
    DashboardServicesServiceIdDomainsRoute,
  DashboardServicesServiceIdServerlessRoute:
    DashboardServicesServiceIdServerlessRoute,
  DashboardServicesServiceIdTerminalRoute:
    DashboardServicesServiceIdTerminalRoute,
  DashboardServicesServiceIdVariablesRoute:
    DashboardServicesServiceIdVariablesRoute,
  DashboardServicesServiceIdIndexRoute: DashboardServicesServiceIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SplatRoute: SplatRoute,
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
